'use client';

import { useEffect, useMemo, useState } from 'react';
import { getBuiltInTemplates } from '@/lib/templates/library';
import { CreateProjectRequest } from '@/lib/generator/schema';
import { derivePromptPackId, getPromptPackDefinition } from '@/lib/generator/prompts';
import { listCodexProfileDefinitions } from '@/lib/generator/profiles';
import { AtlasFigure } from '@/components/atlas-figure';
import { ExecutionDrawer } from '@/components/execution-drawer';
import { MarginNote } from '@/components/margin-note';
import { ProcedureSheet } from '@/components/procedure-sheet';

interface ApiJob {
  id: string;
  state: string;
  result?: Record<string, unknown>;
  error?: string;
}

interface RuntimeConfigStatus {
  NEXTAUTH_URL: 'present' | 'missing';
  NEXTAUTH_SECRET: 'present' | 'missing';
  GITHUB_CLIENT_ID: 'present' | 'missing';
  GITHUB_CLIENT_SECRET: 'present' | 'missing';
}

interface RuntimeConfigCheckResponse {
  githubAuthEnabled: boolean;
  missing: Array<keyof RuntimeConfigStatus>;
  status: RuntimeConfigStatus;
}

interface AuthCheckResponse {
  authenticated: boolean;
  accessTokenPresent: boolean;
  repoCreateCapability: boolean | 'unknown';
  repoListCapability: boolean | 'unknown';
  tokenType: string;
  grantedScopes: string[];
  authStatus:
    | 'valid'
    | 'expired'
    | 'revoked'
    | 'missing_scopes'
    | 'missing_repo_access'
    | 'missing_installation_permissions'
    | 'unknown';
  reauthorizeRequired: boolean;
}

const templates = getBuiltInTemplates();
const codexProfiles = listCodexProfileDefinitions();
const FORM_STORAGE_KEY = 'project-wizard-form-v1';

export const DELIVERY_TARGET_SECTION_TITLE = 'Delivery target and repository behavior';

export const defaultFormState: CreateProjectRequest = {
  schemaVersion: '3.0.0',
  projectName: 'Purview Automation Starter',
  description: 'Deterministic classification and DLP automation scaffold.',
  templateId: 'security-compliance',
  category: 'security-compliance',
  codexProfile: 'strict',
  promptPackId: derivePromptPackId('security-compliance', 'security-compliance'),
  deliveryMode: 'zip',
  github: {
    repoName: 'purview-automation-starter',
    visibility: 'private',
    description: 'Scaffold generated by orchestration app'
  },
  initializeGit: false,
  createBranch: false,
  createWorktree: false
};

function normalizePromptPackState(state: CreateProjectRequest): CreateProjectRequest {
  return {
    ...state,
    promptPackId: derivePromptPackId(state.templateId, state.category)
  };
}

export function resolveGitHubAuthButtons(input: {
  githubRuntimeReady: boolean;
  authenticated: boolean;
  reauthorizeRequired: boolean;
}): { showSignIn: boolean; showReauthorize: boolean; showSignOut: boolean } {
  if (!input.githubRuntimeReady) {
    return { showSignIn: false, showReauthorize: false, showSignOut: input.authenticated };
  }
  if (!input.authenticated) {
    return { showSignIn: true, showReauthorize: false, showSignOut: false };
  }
  if (input.reauthorizeRequired) {
    return { showSignIn: false, showReauthorize: true, showSignOut: true };
  }
  return { showSignIn: false, showReauthorize: false, showSignOut: true };
}

export function usesGitHubDeliveryMode(deliveryMode: CreateProjectRequest['deliveryMode']): boolean {
  return deliveryMode === 'github-new-repo' || deliveryMode === 'github-existing-repo';
}

export function shouldShowGitHubSignInForMode(deliveryMode: CreateProjectRequest['deliveryMode']): boolean {
  return usesGitHubDeliveryMode(deliveryMode);
}

function safeStringifyError(error: unknown): string {
  if (typeof error === 'string') return error;
  return JSON.stringify(error ?? {}, null, 2);
}

function getConsoleState(job: ApiJob | null, error: string | null): 'idle' | 'running' | 'completed' | 'failed' {
  if (error) return 'failed';
  if (!job) return 'idle';
  if (job.state === 'completed') return 'completed';
  if (job.state === 'failed') return 'failed';
  return 'running';
}

export function ProjectWizard() {
  const [formState, setFormState] = useState<CreateProjectRequest>(defaultFormState);
  const [job, setJob] = useState<ApiJob | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [authenticated, setAuthenticated] = useState(false);
  const [githubAuthCheck, setGitHubAuthCheck] = useState<AuthCheckResponse | null>(null);
  const [repos, setRepos] = useState<Array<{ full_name: string }>>([]);
  const [repoSearch, setRepoSearch] = useState('');
  const [loadingRepos, setLoadingRepos] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [runtimeConfig, setRuntimeConfig] = useState<RuntimeConfigCheckResponse | null>(null);

  const selectedTemplate = useMemo(
    () => templates.find((template) => template.id === formState.templateId),
    [formState.templateId]
  );

  const githubRuntimeReady = useMemo(() => runtimeConfig?.githubAuthEnabled === true, [runtimeConfig]);
  const githubSessionUsable = useMemo(
    () => authenticated && githubAuthCheck?.accessTokenPresent === true,
    [authenticated, githubAuthCheck]
  );

  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(FORM_STORAGE_KEY);
      if (!raw) return;
      const parsed = JSON.parse(raw) as Partial<CreateProjectRequest>;
      setFormState((current) =>
        normalizePromptPackState({
          ...current,
          ...parsed,
          github: {
            repoName: parsed.github?.repoName ?? current.github?.repoName ?? defaultFormState.github!.repoName,
            visibility: parsed.github?.visibility ?? current.github?.visibility ?? defaultFormState.github!.visibility,
            description: parsed.github?.description ?? current.github?.description ?? defaultFormState.github!.description,
            existingRepoFullName: parsed.github?.existingRepoFullName ?? current.github?.existingRepoFullName
          }
        })
      );
    } catch {
      window.localStorage.removeItem(FORM_STORAGE_KEY);
    }
  }, []);

  useEffect(() => {
    setFormState((current) => normalizePromptPackState(current));
  }, [formState.templateId, formState.category]);

  useEffect(() => {
    window.localStorage.setItem(FORM_STORAGE_KEY, JSON.stringify(formState));
  }, [formState]);

  useEffect(() => {
    fetch('/api/auth/session')
      .then((response) => response.json())
      .then((data: { authenticated?: boolean }) => setAuthenticated(Boolean(data.authenticated)))
      .catch(() => setAuthenticated(false));

    fetch('/api/github/auth-check')
      .then((response) => response.json())
      .then((data: AuthCheckResponse) => setGitHubAuthCheck(data))
      .catch(() => setGitHubAuthCheck(null));

    fetch('/api/runtime-config-check')
      .then((response) => response.json())
      .then((data: RuntimeConfigCheckResponse) => setRuntimeConfig(data))
      .catch(() => setRuntimeConfig(null));
  }, []);

  useEffect(() => {
    if (formState.deliveryMode !== 'github-existing-repo' || !githubSessionUsable || !githubRuntimeReady) {
      setRepos([]);
      return;
    }

    const controller = new AbortController();
    setLoadingRepos(true);

    fetch(`/api/github/repos?page=1&search=${encodeURIComponent(repoSearch.trim())}`, { signal: controller.signal })
      .then((response) => response.json())
      .then((data: { repos?: Array<{ full_name: string }> }) =>
        setRepos((data.repos ?? []).sort((a, b) => a.full_name.localeCompare(b.full_name)))
      )
      .catch(() => setRepos([]))
      .finally(() => setLoadingRepos(false));

    return () => controller.abort();
  }, [formState.deliveryMode, githubRuntimeReady, githubSessionUsable, repoSearch]);

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (submitting) return;

    setError(null);
    setJob({ id: 'pending', state: 'running' });
    setSubmitting(true);

    try {
      const response = await fetch('/api/projects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formState)
      });

      const body = (await response.json()) as { job?: ApiJob; error?: unknown };
      if (!response.ok || !body.job) {
        setJob(null);
        setError(safeStringifyError(body.error ?? body));
        return;
      }

      setJob(body.job);
    } catch {
      setJob(null);
      setError('Network error while submitting project generation request.');
    } finally {
      setSubmitting(false);
    }
  }

  const buttonState = resolveGitHubAuthButtons({
    githubRuntimeReady,
    authenticated,
    reauthorizeRequired: githubAuthCheck?.reauthorizeRequired === true
  });

  const downloadUrl = job?.state === 'completed' && formState.deliveryMode === 'zip' ? `/api/jobs/${job.id}/download` : null;
  const consoleState = getConsoleState(job, error);
  const showGitHubAuthControls = shouldShowGitHubSignInForMode(formState.deliveryMode);
  const promptPackDefinition = useMemo(
    () => getPromptPackDefinition(formState.templateId, formState.category),
    [formState.category, formState.templateId]
  );
  const selectedCodexProfile = useMemo(
    () => codexProfiles.find((profile) => profile.id === formState.codexProfile),
    [formState.codexProfile]
  );

  return (
    <form className="atlas-layout" onSubmit={submit}>
      <div className="procedure-flow">
        <section className="context-stack" aria-label="Workflow context">
          <MarginNote title="Workflow diagrams">
            <p>Review the generation and delivery flow before executing so mode-specific behavior is explicit.</p>
            <AtlasFigure src="/images/workflow-overview.svg" alt="Workflow overview" />
            <AtlasFigure src="/images/delivery-mode-flow.svg" alt="Delivery mode flow" />
          </MarginNote>
          <MarginNote title="Delivery path summary">
            <ul>
              <li>Download ZIP creates a local artifact bundle and requires no GitHub authentication.</li>
              <li>Create new repo provisions a new repository and commits generated scaffold files.</li>
              <li>Update existing repo creates branch + PR output and applies `_ops` suffixing to generated paths.</li>
            </ul>
          </MarginNote>
          <MarginNote title="Safety rules">
            <ul>
              <li>Unsafe or sensitive paths are blocked before writing output.</li>
              <li>Existing-repository delivery is isolated to generated `_ops` paths to avoid collisions.</li>
              <li>Execution payloads include deterministic ordering, checksums, and hygiene metadata.</li>
            </ul>
          </MarginNote>
          <MarginNote title="Selected template context">
            <p>Template: {selectedTemplate?.name ?? 'Unknown template'}.</p>
            <p>{selectedTemplate?.description ?? 'No template description available.'}</p>
          </MarginNote>
        </section>

        <ProcedureSheet
          title="Project identity"
          description="Define the project name and purpose used in scaffold metadata, generated README content, and manifest details."
        >
          <div className="field-cluster">
            <label>
              Project name
              <input
                required
                value={formState.projectName}
                onChange={(event) => setFormState((state) => ({ ...state, projectName: event.target.value }))}
              />
            </label>
            <label>
              Description
              <textarea
                required
                value={formState.description}
                onChange={(event) => setFormState((state) => ({ ...state, description: event.target.value }))}
              />
            </label>
          </div>
        </ProcedureSheet>

        <ProcedureSheet
          title="Template, category, and profile"
          description="Select the scaffold structure and policy profile that determine generated files, prompts, and implementation guidance."
        >
          <div className="field-cluster field-cluster--grid">
            <label>
              Stack template
              <select
                value={formState.templateId}
                onChange={(event) =>
                  setFormState((state) =>
                    normalizePromptPackState({ ...state, templateId: event.target.value as CreateProjectRequest['templateId'] })
                  )
                }
              >
                {templates.map((template) => (
                  <option key={template.id} value={template.id}>
                    {template.name}
                  </option>
                ))}
              </select>
            </label>
            <label>
              Category
              <select
                value={formState.category}
                onChange={(event) =>
                  setFormState((state) =>
                    normalizePromptPackState({ ...state, category: event.target.value as CreateProjectRequest['category'] })
                  )
                }
              >
                <option value="web-platform">Web platform</option>
                <option value="api-service">API service</option>
                <option value="automation">Automation</option>
                <option value="security-compliance">Security/compliance</option>
                <option value="research">Research</option>
              </select>
            </label>
            <label>
              Codex profile
              <select
                value={formState.codexProfile}
                onChange={(event) =>
                  setFormState((state) => ({ ...state, codexProfile: event.target.value as CreateProjectRequest['codexProfile'] }))
                }
              >
                {codexProfiles.map((profile) => (
                  <option key={profile.id} value={profile.id}>
                    {profile.label}
                  </option>
                ))}
              </select>
            </label>
          </div>
          <p className="field-hint">{selectedCodexProfile?.helpText}</p>
        </ProcedureSheet>

        <ProcedureSheet
          title={DELIVERY_TARGET_SECTION_TITLE}
          description="Choose where generated artifacts are delivered and how repository safety rules are applied."
        >
          <div className="field-cluster field-cluster--grid">
            <label>
              Delivery mode
              <select
                value={formState.deliveryMode}
                onChange={(event) =>
                  setFormState((state) => ({
                    ...state,
                    deliveryMode: event.target.value as CreateProjectRequest['deliveryMode']
                  }))
                }
              >
                <option value="zip">Download ZIP</option>
                <option value="github-new-repo">Create new repo</option>
                <option value="github-existing-repo">Update existing repo</option>
              </select>
            </label>
            <label>
              Prompt pack
              <input value={promptPackDefinition.id} readOnly />
            </label>
          </div>
          <p className="field-hint">Prompt pack is automatically tailored from Stack template + Category.</p>
          <p className="field-hint">
            {promptPackDefinition.label}: {promptPackDefinition.description}
          </p>

          {formState.deliveryMode === 'zip' ? <p className="field-hint">Download ZIP runs locally and does not require GitHub authentication.</p> : null}
          {formState.deliveryMode === 'github-new-repo' ? (
            <p className="field-hint">Create new repo uses GitHub to create a destination repository and commit generated scaffold files.</p>
          ) : null}
          {formState.deliveryMode === 'github-existing-repo' ? (
            <p className="field-hint">Update existing repo uses GitHub branch + PR delivery and applies `_ops` suffixes to generated paths to avoid collisions.</p>
          ) : null}

          {showGitHubAuthControls ? (
            <div className="field-cluster">
              <p className="field-hint">GitHub delivery mode selected. Authenticate to enable repository creation or repository selection.</p>
              <div className="field-row">
                {buttonState.showSignIn ? (
                  <button
                    type="button"
                    onClick={() =>
                      (window.location.href = `/api/auth/signin/github?callbackUrl=${encodeURIComponent(window.location.href)}&scope=${encodeURIComponent('read:user user:email repo')}`)
                    }
                  >
                    Sign in with GitHub
                  </button>
                ) : null}
                {buttonState.showReauthorize ? (
                  <button
                    type="button"
                    onClick={() =>
                      (window.location.href = `/api/auth/signin/github?callbackUrl=${encodeURIComponent(window.location.href)}&scope=${encodeURIComponent('read:user user:email repo')}`)
                    }
                  >
                    Re-authorize
                  </button>
                ) : null}
                {buttonState.showSignOut ? (
                  <button type="button" onClick={() => (window.location.href = '/api/auth/signout?callbackUrl=/')}>
                    Sign out
                  </button>
                ) : null}
              </div>
            </div>
          ) : null}

          {formState.deliveryMode === 'github-new-repo' ? (
            <div className="field-cluster field-cluster--grid-3">
              <label>
                Repository name
                <input
                  required
                  value={formState.github?.repoName ?? ''}
                  onChange={(event) =>
                    setFormState((state) => ({
                      ...state,
                      github: {
                        ...state.github,
                        repoName: event.target.value,
                        visibility: state.github?.visibility ?? 'private'
                      }
                    }))
                  }
                />
              </label>
              <label>
                Visibility
                <select
                  value={formState.github?.visibility ?? 'private'}
                  onChange={(event) =>
                    setFormState((state) => ({
                      ...state,
                      github: {
                        ...state.github,
                        visibility: event.target.value as 'public' | 'private',
                        repoName: state.github?.repoName ?? ''
                      }
                    }))
                  }
                >
                  <option value="private">Private</option>
                  <option value="public">Public</option>
                </select>
              </label>
              <label>
                Repository description
                <input
                  value={formState.github?.description ?? ''}
                  onChange={(event) =>
                    setFormState((state) => ({
                      ...state,
                      github: {
                        ...state.github,
                        description: event.target.value,
                        repoName: state.github?.repoName ?? '',
                        visibility: state.github?.visibility ?? 'private'
                      }
                    }))
                  }
                />
              </label>
            </div>
          ) : null}

          {formState.deliveryMode === 'github-existing-repo' ? (
            <div className="field-cluster field-cluster--grid">
              <label>
                Search repositories
                <input value={repoSearch} placeholder="owner/repository" onChange={(event) => setRepoSearch(event.target.value)} />
              </label>
              <label>
                Existing repository
                <select
                  value={formState.github?.existingRepoFullName ?? ''}
                  onChange={(event) =>
                    setFormState((state) => ({
                      ...state,
                      github: {
                        ...state.github,
                        existingRepoFullName: event.target.value,
                        repoName: state.github?.repoName ?? 'placeholder',
                        visibility: state.github?.visibility ?? 'private'
                      }
                    }))
                  }
                >
                  <option value="">{loadingRepos ? 'Loading repositories...' : 'Select repository'}</option>
                  {repos.map((repo) => (
                    <option key={repo.full_name} value={repo.full_name}>
                      {repo.full_name}
                    </option>
                  ))}
                </select>
              </label>
            </div>
          ) : null}
        </ProcedureSheet>

        <ProcedureSheet
          title="Generate delivery package"
          description="Submit the configured request and inspect deterministic output metadata in the execution console."
        >
          <div className="field-row">
            <button
              type="submit"
              disabled={submitting || (showGitHubAuthControls && (!githubSessionUsable || !githubRuntimeReady))}
            >
              {submitting ? 'Generating project files...' : 'Generate project files'}
            </button>
          </div>
        </ProcedureSheet>
      </div>

      <ExecutionDrawer state={consoleState}>
        {consoleState === 'idle' ? <p>No generation jobs executed yet. Configure options and run project file generation.</p> : null}

        {consoleState === 'running' ? <p>Generation request accepted. Waiting for /api/projects completion payload.</p> : null}

        {job && job.state !== 'running' ? (
          <>
            <p>
              Job <code>{job.id}</code> completed with state <strong>{job.state}</strong>.
            </p>
            <pre>{JSON.stringify(job, null, 2)}</pre>
          </>
        ) : null}

        {downloadUrl ? (
          <a className="download-link" href={downloadUrl} target="_blank" rel="noreferrer">
            Download ZIP artifact
          </a>
        ) : null}

        {error ? (
          <>
            <p>Generation failed</p>
            <pre>{error}</pre>
          </>
        ) : null}
      </ExecutionDrawer>
    </form>
  );
}
