'use client';

import { useEffect, useMemo, useState } from 'react';
import { getBuiltInTemplates } from '@/lib/templates/library';
import { CreateProjectRequest } from '@/lib/generator/schema';

interface ApiJob {
  id: string;
  state: string;
  result?: Record<string, unknown>;
  error?: string;
}

interface RuntimeConfigStatus {
  NEXTAUTH_URL: 'present' | 'missing';
  NEXTAUTH_SECRET: 'present' | 'missing';
  GITHUB_CLIENT_ID: 'present' | 'missing';
  GITHUB_CLIENT_SECRET: 'present' | 'missing';
}

interface RuntimeConfigCheckResponse {
  githubAuthEnabled: boolean;
  missing: Array<keyof RuntimeConfigStatus>;
  status: RuntimeConfigStatus;
}

interface AuthCheckResponse {
  authenticated: boolean;
  accessTokenPresent: boolean;
  repoCreateCapability: boolean | 'unknown';
  repoListCapability: boolean | 'unknown';
  tokenType: string;
  grantedScopes: string[];
  authStatus:
    | 'valid'
    | 'expired'
    | 'revoked'
    | 'missing_scopes'
    | 'missing_repo_access'
    | 'missing_installation_permissions'
    | 'unknown';
  reauthorizeRequired: boolean;
}

const templates = getBuiltInTemplates();
const FORM_STORAGE_KEY = 'project-wizard-form-v1';

export function resolveGitHubAuthButtons(input: {
  githubRuntimeReady: boolean;
  authenticated: boolean;
  reauthorizeRequired: boolean;
}): { showSignIn: boolean; showReauthorize: boolean; showSignOut: boolean } {
  if (!input.githubRuntimeReady) {
    return { showSignIn: false, showReauthorize: false, showSignOut: input.authenticated };
  }
  if (!input.authenticated) {
    return { showSignIn: true, showReauthorize: false, showSignOut: false };
  }
  if (input.reauthorizeRequired) {
    return { showSignIn: false, showReauthorize: true, showSignOut: true };
  }
  return { showSignIn: false, showReauthorize: false, showSignOut: true };
}

const defaultForm: CreateProjectRequest = {
  schemaVersion: '3.0.0',
  projectName: 'Purview Automation Starter',
  description: 'Deterministic classification and DLP automation scaffold.',
  templateId: 'security-compliance',
  category: 'security-compliance',
  codexProfile: 'strict',
  promptPackId: 'security-compliance-focused',
  deliveryMode: 'zip',
  github: {
    repoName: 'purview-automation-starter',
    visibility: 'private',
    description: 'Scaffold generated by orchestration app'
  },
  initializeGit: false,
  createBranch: false,
  createWorktree: false
};

function safeStringifyError(error: unknown): string {
  if (typeof error === 'string') return error;
  return JSON.stringify(error ?? {}, null, 2);
}

export function ProjectWizard() {
  const [formState, setFormState] = useState<CreateProjectRequest>(defaultForm);
  const [job, setJob] = useState<ApiJob | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [authenticated, setAuthenticated] = useState(false);
  const [githubAuthCheck, setGitHubAuthCheck] = useState<AuthCheckResponse | null>(null);
  const [repos, setRepos] = useState<Array<{ full_name: string }>>([]);
  const [repoSearch, setRepoSearch] = useState('');
  const [loadingRepos, setLoadingRepos] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [runtimeConfig, setRuntimeConfig] = useState<RuntimeConfigCheckResponse | null>(null);

  const selectedTemplate = useMemo(
    () => templates.find((template) => template.id === formState.templateId),
    [formState.templateId]
  );

  const githubRuntimeReady = useMemo(() => {
    if (!runtimeConfig) return false;
    return runtimeConfig.githubAuthEnabled;
  }, [runtimeConfig]);

  const githubSessionUsable = useMemo(
    () => authenticated && githubAuthCheck?.accessTokenPresent === true,
    [authenticated, githubAuthCheck]
  );

  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(FORM_STORAGE_KEY);
      if (!raw) return;
      const parsed = JSON.parse(raw) as Partial<CreateProjectRequest>;
      setFormState((current) => ({
        ...current,
        ...parsed,
        github: {
          repoName: parsed.github?.repoName ?? current.github?.repoName ?? defaultForm.github!.repoName,
          visibility: parsed.github?.visibility ?? current.github?.visibility ?? defaultForm.github!.visibility,
          description: parsed.github?.description ?? current.github?.description ?? defaultForm.github!.description,
          existingRepoFullName: parsed.github?.existingRepoFullName ?? current.github?.existingRepoFullName
        }
      }));
    } catch {
      window.localStorage.removeItem(FORM_STORAGE_KEY);
    }
  }, []);

  useEffect(() => {
    window.localStorage.setItem(FORM_STORAGE_KEY, JSON.stringify(formState));
  }, [formState]);

  useEffect(() => {
    fetch('/api/auth/session')
      .then((response) => response.json())
      .then((data: { authenticated?: boolean }) => setAuthenticated(Boolean(data.authenticated)))
      .catch(() => setAuthenticated(false));

    fetch('/api/github/auth-check')
      .then((response) => response.json())
      .then((data: AuthCheckResponse) => setGitHubAuthCheck(data))
      .catch(() => setGitHubAuthCheck(null));

    fetch('/api/runtime-config-check')
      .then((response) => response.json())
      .then((data: RuntimeConfigCheckResponse) => setRuntimeConfig(data))
      .catch(() => setRuntimeConfig(null));
  }, []);

  useEffect(() => {
    if (formState.deliveryMode !== 'github-existing-repo' || !githubSessionUsable || !githubRuntimeReady) {
      setRepos([]);
      return;
    }

    const controller = new AbortController();
    setLoadingRepos(true);

    fetch(`/api/github/repos?page=1&search=${encodeURIComponent(repoSearch.trim())}`, { signal: controller.signal })
      .then((response) => response.json())
      .then((data: { repos?: Array<{ full_name: string }> }) =>
        setRepos((data.repos ?? []).sort((a, b) => a.full_name.localeCompare(b.full_name)))
      )
      .catch(() => setRepos([]))
      .finally(() => setLoadingRepos(false));

    return () => controller.abort();
  }, [formState.deliveryMode, githubRuntimeReady, githubSessionUsable, repoSearch]);

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (submitting) return;

    setError(null);
    setJob(null);
    setSubmitting(true);

    try {
      const res = await fetch('/api/projects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formState)
      });

      const body = (await res.json()) as { job?: ApiJob; error?: unknown };
      if (!res.ok || !body.job) {
        setError(safeStringifyError(body.error ?? body));
        return;
      }

      setJob(body.job);
    } catch {
      setError('Network error while submitting orchestration request.');
    } finally {
      setSubmitting(false);
    }
  }

  const oauthDisabledReason = githubRuntimeReady
    ? null
    : `GitHub authentication is unavailable: missing ${runtimeConfig?.missing.join(', ') ?? 'runtime configuration'}.`;

  const authStatusText = githubSessionUsable ? 'Connected' : 'Not connected';
  const repoCreateMissingPermission = githubSessionUsable && githubAuthCheck?.repoCreateCapability === false;
  const repoListMissingPermission = githubSessionUsable && githubAuthCheck?.repoListCapability === false;
  const buttonState = resolveGitHubAuthButtons({
    githubRuntimeReady,
    authenticated,
    reauthorizeRequired: githubAuthCheck?.reauthorizeRequired === true
  });

  const downloadUrl = job?.state === 'completed' && formState.deliveryMode === 'zip' ? `/api/jobs/${job.id}/download` : null;

  return (
    <section className="wizard-shell">
      <form className="panel workspace-panel" onSubmit={submit}>
        <header className="panel-header">
          <h2>Project orchestration workspace</h2>
          <p>Submit deterministic scaffold jobs with explicit delivery and repository controls.</p>
        </header>

        <div className="panel-body form-stack">
          <section className="field-section">
            <div className="section-title-row">
              <h3>GitHub authorization</h3>
              <span className={`status-badge ${githubSessionUsable ? 'ok' : 'idle'}`}>{authStatusText}</span>
            </div>
            {oauthDisabledReason && <p className="warning">{oauthDisabledReason}</p>}
            {repoCreateMissingPermission && (
              <p className="warning">
                Connected to GitHub, but token lacks repository creation permission. Re-authentication may be required.
              </p>
            )}
            {repoListMissingPermission && (
              <p className="warning">
                Connected to GitHub, but token cannot list repositories for existing-repo mode. Re-authentication may be
                required.
              </p>
            )}
            <div className="button-row wrap">
              {buttonState.showSignIn && (
                <button
                  type="button"
                  onClick={() =>
                    (window.location.href = `/api/auth/signin/github?callbackUrl=${encodeURIComponent(window.location.href)}&scope=${encodeURIComponent('read:user user:email repo')}`)
                  }
                >
                  Sign in with GitHub
                </button>
              )}
              {buttonState.showReauthorize && (
                <button
                  type="button"
                  onClick={() =>
                    (window.location.href = `/api/auth/signin/github?callbackUrl=${encodeURIComponent(window.location.href)}&scope=${encodeURIComponent('read:user user:email repo')}`)
                  }
                >
                  Re-authorize GitHub
                </button>
              )}
              {buttonState.showSignOut && (
                <button type="button" onClick={() => (window.location.href = '/api/auth/signout?callbackUrl=/')}>
                  Sign out
                </button>
              )}
            </div>
          </section>

          <section className="field-section">
            <h3>Project inputs</h3>
            <label>
              Project Name
              <input
                required
                value={formState.projectName}
                onChange={(e) => setFormState((s) => ({ ...s, projectName: e.target.value }))}
              />
            </label>
            <label>
              Description
              <textarea
                required
                value={formState.description}
                onChange={(e) => setFormState((s) => ({ ...s, description: e.target.value }))}
              />
            </label>
            <label>
              Stack Template
              <select
                value={formState.templateId}
                onChange={(e) =>
                  setFormState((s) => ({ ...s, templateId: e.target.value as CreateProjectRequest['templateId'] }))
                }
              >
                {templates.map((template) => (
                  <option key={template.id} value={template.id}>
                    {template.name}
                  </option>
                ))}
              </select>
            </label>
            <label>
              Category
              <select
                value={formState.category}
                onChange={(e) =>
                  setFormState((s) => ({ ...s, category: e.target.value as CreateProjectRequest['category'] }))
                }
              >
                <option value="web-platform">Web platform</option>
                <option value="api-service">API service</option>
                <option value="automation">Automation</option>
                <option value="security-compliance">Security/compliance</option>
                <option value="research">Research</option>
              </select>
            </label>
          </section>

          <section className="field-section">
            <h3>Delivery mode</h3>
            <label>
              Mode
              <select
                value={formState.deliveryMode}
                onChange={(e) =>
                  setFormState((s) => ({ ...s, deliveryMode: e.target.value as CreateProjectRequest['deliveryMode'] }))
                }
              >
                <option value="zip">Download zipped bundle</option>
                <option value="github-new-repo">Create new GitHub repo</option>
                <option value="github-existing-repo">Update existing repo (PR)</option>
              </select>
            </label>
          </section>

          {formState.deliveryMode === 'github-new-repo' && (
            <section className="field-section">
              <h3>Repository target (new)</h3>
              <label>
                Repo Name
                <input
                  required
                  value={formState.github?.repoName ?? ''}
                  onChange={(e) =>
                    setFormState((s) => ({
                      ...s,
                      github: { ...s.github, repoName: e.target.value, visibility: s.github?.visibility ?? 'private' }
                    }))
                  }
                />
              </label>
              <label>
                Visibility
                <select
                  value={formState.github?.visibility ?? 'private'}
                  onChange={(e) =>
                    setFormState((s) => ({
                      ...s,
                      github: {
                        ...s.github,
                        visibility: e.target.value as 'public' | 'private',
                        repoName: s.github?.repoName ?? ''
                      }
                    }))
                  }
                >
                  <option value="private">Private</option>
                  <option value="public">Public</option>
                </select>
              </label>
              <label>
                Description
                <input
                  value={formState.github?.description ?? ''}
                  onChange={(e) =>
                    setFormState((s) => ({
                      ...s,
                      github: {
                        ...s.github,
                        description: e.target.value,
                        repoName: s.github?.repoName ?? '',
                        visibility: s.github?.visibility ?? 'private'
                      }
                    }))
                  }
                />
              </label>
            </section>
          )}

          {formState.deliveryMode === 'github-existing-repo' && (
            <section className="field-section">
              <h3>Repository target (existing)</h3>
              <label>
                Search repositories
                <input
                  value={repoSearch}
                  placeholder="owner/repository"
                  onChange={(e) => setRepoSearch(e.target.value)}
                />
              </label>
              <label>
                Existing Repository
                <select
                  value={formState.github?.existingRepoFullName ?? ''}
                  onChange={(e) =>
                    setFormState((s) => ({
                      ...s,
                      github: {
                        ...s.github,
                        existingRepoFullName: e.target.value,
                        repoName: s.github?.repoName ?? 'placeholder',
                        visibility: s.github?.visibility ?? 'private'
                      }
                    }))
                  }
                >
                  <option value="">{loadingRepos ? 'Loading repositories...' : 'Select a repository'}</option>
                  {repos.map((repo) => (
                    <option key={repo.full_name} value={repo.full_name}>
                      {repo.full_name}
                    </option>
                  ))}
                </select>
              </label>
            </section>
          )}

          <section className="field-section">
            <h3>Execution controls</h3>
            <button
              type="submit"
              disabled={submitting || (formState.deliveryMode !== 'zip' && (!githubSessionUsable || !githubRuntimeReady))}
            >
              {submitting ? 'Running orchestration...' : 'Run Orchestration'}
            </button>
          </section>
        </div>
      </form>

      <aside className="panel reference-panel">
        <header className="panel-header">
          <h2>Automation boundary</h2>
          <p>Inspection panel for delivery restrictions and template context.</p>
        </header>
        <div className="panel-body">
          <ul>
            <li>ZIP mode works without GitHub login.</li>
            <li>GitHub modes require OAuth login.</li>
            <li>Existing repo mode is PR-only and non-destructive.</li>
            <li>OAuth flow uses full-page redirects for mobile browser compatibility.</li>
          </ul>

          <div className="template-list">
            {templates.map((template) => (
              <article key={template.id} className={template.id === selectedTemplate?.id ? 'template-item active-template' : 'template-item'}>
                <h3>{template.name}</h3>
                <p>{template.description}</p>
              </article>
            ))}
          </div>
        </div>
      </aside>

      <section className="panel result-console">
        <header className="panel-header">
          <h2>Execution log and results</h2>
          <p>Job state, payload details, and download actions.</p>
        </header>
        <div className="panel-body">
          {!job && <p>No job yet. Submit the workspace form to execute orchestration.</p>}
          {job && (
            <div>
              <p>
                <span className="status-badge ok">State: {job.state}</span>
              </p>
              <pre>{JSON.stringify(job, null, 2)}</pre>
            </div>
          )}
          {downloadUrl && (
            <div className="button-row">
              <a className="button-link" href={downloadUrl} target="_blank" rel="noreferrer">
                Download ZIP
              </a>
            </div>
          )}
          {error && <pre className="error">{error}</pre>}
        </div>
      </section>
    </section>
  );
}
